// src/api/categories/dummy-data.ts
import { Category } from "@/types";

export const categories: Category[] = [
  {
    id: "cat-001",
    name: "UPVC Works",
    tagline: "Elegant and durable designs for modern spaces",
    description:
      "We offer premium glass solutions including doors, partitions, railings, and windows. Each product is crafted to deliver long-lasting beauty and strength.",
    cardBannerUrl: "https://example.com/images/upvc-card-banner.jpg",
    detailsBannerUrl: "https://example.com/images/upvc-details-banner.jpg",
    isPremium: true,
    isRepairingService: false,
    isShowHome: true,
    sortOrder: 1,
    userId: "cmgs8jhqy0000ghrwl9omgzi2",
    addons: [
      "Tempered Glass",
      "Sliding Door",
      "Mirror Installation",
      "Partition Setup",
    ],
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-03-20T14:45:00Z",
  },
  {
    id: "cat-002",
    name: "Aluminum Fabrication",
    tagline: "Lightweight and strong aluminum solutions",
    description:
      "Expert aluminum fabrication services for windows, doors, railings, and structural components. Weather-resistant and low maintenance.",
    cardBannerUrl: "https://example.com/images/aluminum-card-banner.jpg",
    detailsBannerUrl: "https://example.com/images/aluminum-details-banner.jpg",
    isPremium: true,
    isRepairingService: true,
    isShowHome: true,
    sortOrder: 2,
    userId: "cmgs8jhqy0000ghrwl9omgzi2",
    addons: [
      "Powder Coating",
      "Anodized Finish",
      "Custom Designs",
      "Installation",
    ],
    createdAt: "2024-01-20T09:15:00Z",
    updatedAt: "2024-03-18T11:20:00Z",
  },
  {
    id: "cat-003",
    name: "Steel Fabrication",
    tagline: "Heavy-duty steel structures and solutions",
    description:
      "Complete steel fabrication and welding services for gates, grills, staircases, and structural supports. Built to last.",
    cardBannerUrl: "https://example.com/images/steel-card-banner.jpg",
    detailsBannerUrl: "https://example.com/images/steel-details-banner.jpg",
    isPremium: false,
    isRepairingService: true,
    isShowHome: true,
    sortOrder: 3,
    userId: "cmgs8jhqy0000ghrwl9omgzi2",
    addons: ["MS Gate", "SS Railing", "Welding", "Galvanization"],
    createdAt: "2024-02-01T08:00:00Z",
    updatedAt: "2024-03-15T16:30:00Z",
  },
  {
    id: "cat-004",
    name: "Glass Works",
    tagline: "Crystal clear glass installations",
    description:
      "Professional glass installation services including shower enclosures, glass doors, mirrors, and partitions with modern designs.",
    cardBannerUrl: "https://example.com/images/glass-card-banner.jpg",
    detailsBannerUrl: "https://example.com/images/glass-details-banner.jpg",
    isPremium: true,
    isRepairingService: false,
    isShowHome: false,
    sortOrder: 4,
    userId: "cmgs8jhqy0000ghrwl9omgzi2",
    addons: [
      "Toughened Glass",
      "Laminated Glass",
      "Frosted Glass",
      "Mirror Work",
    ],
    createdAt: "2024-02-10T10:45:00Z",
    updatedAt: "2024-03-12T13:15:00Z",
  },
  {
    id: "cat-005",
    name: "Wooden Carpentry",
    tagline: "Handcrafted wooden furniture and fittings",
    description:
      "Custom wooden furniture, doors, and interior fittings made from premium quality wood with expert craftsmanship.",
    cardBannerUrl: "https://example.com/images/wood-card-banner.jpg",
    detailsBannerUrl: "https://example.com/images/wood-details-banner.jpg",
    isPremium: true,
    isRepairingService: true,
    isShowHome: true,
    sortOrder: 5,
    userId: "cmgs8jhqy0000ghrwl9omgzi2",
    addons: ["Teak Wood", "Sheesham", "Plywood", "Veneer Finish"],
    createdAt: "2024-02-15T11:30:00Z",
    updatedAt: "2024-03-10T09:45:00Z",
  },
  {
    id: "cat-006",
    name: "False Ceiling",
    tagline: "Modern ceiling solutions for all spaces",
    description:
      "POP, gypsum, and grid false ceiling installation with LED integration and modern designs for homes and offices.",
    cardBannerUrl: "https://example.com/images/ceiling-card-banner.jpg",
    detailsBannerUrl: "https://example.com/images/ceiling-details-banner.jpg",
    isPremium: false,
    isRepairingService: false,
    isShowHome: true,
    sortOrder: 6,
    userId: "cmgs8jhqy0000ghrwl9omgzi2",
    addons: ["POP Ceiling", "Gypsum Board", "LED Integration", "Grid Ceiling"],
    createdAt: "2024-02-20T14:00:00Z",
    updatedAt: "2024-03-08T10:30:00Z",
  },
  {
    id: "cat-007",
    name: "Electrical Services",
    tagline: "Complete electrical solutions",
    description:
      "Full-service electrical installation, repair, and maintenance including wiring, panel setup, and smart home automation.",
    cardBannerUrl: "https://example.com/images/electrical-card-banner.jpg",
    detailsBannerUrl:
      "https://example.com/images/electrical-details-banner.jpg",
    isPremium: false,
    isRepairingService: true,
    isShowHome: false,
    sortOrder: 7,
    userId: "cmgs8jhqy0000ghrwl9omgzi2",
    addons: ["Wiring", "Panel Board", "Smart Switches", "LED Lighting"],
    createdAt: "2024-02-25T09:30:00Z",
    updatedAt: "2024-03-05T15:20:00Z",
  },
  {
    id: "cat-008",
    name: "Plumbing Services",
    tagline: "Expert plumbing and sanitation",
    description:
      "Comprehensive plumbing services for residential and commercial properties including installation, repair, and maintenance.",
    cardBannerUrl: "https://example.com/images/plumbing-card-banner.jpg",
    detailsBannerUrl: "https://example.com/images/plumbing-details-banner.jpg",
    isPremium: false,
    isRepairingService: true,
    isShowHome: true,
    sortOrder: 8,
    userId: "cmgs8jhqy0000ghrwl9omgzi2",
    addons: ["Pipe Fitting", "Bathroom Fitting", "Kitchen Sink", "Water Tank"],
    createdAt: "2024-03-01T08:45:00Z",
    updatedAt: "2024-03-03T12:00:00Z",
  },
  {
    id: "cat-009",
    name: "Painting Services",
    tagline: "Professional painting and finishing",
    description:
      "Interior and exterior painting services with premium quality paints, texture work, and decorative finishes.",
    cardBannerUrl: "https://example.com/images/painting-card-banner.jpg",
    detailsBannerUrl: "https://example.com/images/painting-details-banner.jpg",
    isPremium: true,
    isRepairingService: false,
    isShowHome: true,
    sortOrder: 9,
    userId: "cmgs8jhqy0000ghrwl9omgzi2",
    addons: ["Texture Paint", "Asian Paints", "Dulux", "Stencil Work"],
    createdAt: "2024-03-05T10:00:00Z",
    updatedAt: "2024-03-20T14:30:00Z",
  },
  {
    id: "cat-010",
    name: "Waterproofing",
    tagline: "Complete waterproofing solutions",
    description:
      "Advanced waterproofing treatments for roofs, terraces, bathrooms, and basements with long-lasting protection.",
    cardBannerUrl: "https://example.com/images/waterproof-card-banner.jpg",
    detailsBannerUrl:
      "https://example.com/images/waterproof-details-banner.jpg",
    isPremium: true,
    isRepairingService: true,
    isShowHome: false,
    sortOrder: 10,
    userId: "cmgs8jhqy0000ghrwl9omgzi2",
    addons: [
      "Terrace Treatment",
      "Bathroom Sealing",
      "Chemical Treatment",
      "APP Membrane",
    ],
    createdAt: "2024-03-10T11:15:00Z",
    updatedAt: "2024-03-18T16:45:00Z",
  },
];

export type { Category };
